global:
  scrape_interval: 30s

rule_files: 
- '/etc/prometheus/rules.yml' # volume mounted in docker-compose, comes from ./prometheus at host

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - 'alertmanager:9093'

scrape_configs:
- job_name: 'node-exporter'
  static_configs:
    - targets:
      - 'node_exporter:9100'
